name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libcjson-dev
      - name: Build tests
        run: make -C tests
      - name: Run tests
        run: |
          for bin in tests/test_*; do
            if [ -x "$bin" ]; then
              "$bin"
            fi
          done

  idf-build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Build firmware
        run: idf.py build
